version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: build/docker/dev/Dockerfile
    volumes:
      - ./:/app/
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    environment:
      # Use test enviroment
      APP_ADDRESS: ":3000"
      APP_DSN: "host=postgresql user=admin password=admin dbname=app port=5432"
    healthcheck:
      test: ["CMD-SHELL", "cat", "/tmp/app_server_live"]
      interval: 5s
      timeout: 10s
      retries: 5
  postgresql:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
      PGDATA: /data/postgres
    volumes:
      - postgresql_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  migrate:
    image: migrate/migrate
    volumes:
      - ./database/:/database
    command:
      - "-path"
      - "/database/migrations"
      - "-database"
      - "postgres://admin:admin@postgresql:5432/app?sslmode=disable"
      - "up"
    depends_on:
      - postgresql

volumes:
  postgresql_data:
