version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: build/package/dev/Dockerfile
    volumes:
      - ./:/app/
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
  postgresql:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
      PGDATA: /data/postgres
    volumes:
       - postgresql_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgresql_data:
